services:
  traefik:
    image: "traefik:v3.4"
    network_mode: host
    environment:
      TRAEFIK_LOG_LEVEL: "DEBUG"
      TRAEFIK_ENTRYPOINTS_TRAEFIK_ADDRESS: ":8080"
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":81"
      TRAEFIK_API_INSECURE: true
      TRAEFIK_PING_ENTRYPOINT: "traefik"
      TRAEFIK_PROVIDERS_HTTP_ENDPOINT: "http://0.0.0.0:4000/configuration"
      TRAEFIK_PROVIDERS_HTTP_POLLINTERVAL: "5s"
      TRAEFIK_TRACING_OTLP_HTTP_ENDPOINT: "http://0.0.0.0:4318/v1/traces"
      TRAEFIK_METRICS_OTLP_HTTP_ENDPOINT: "http://0.0.0.0:4318/v1/metrics"

  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    ports:
      - 16686:16686 # serve frontend
    command:
      - "--collector.otlp.http.cors.allowed-headers=*"
      - "--collector.otlp.http.cors.allowed-origins=*"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4318:4318" # OTLP HTTP receiver
      - "4317:4317" # OTLP gRPC receiver
      - "9474:9474" # Prometheus receiver
    volumes:
      - ./docker/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger

