name: Create release

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/mach-composer/mach-composer

jobs:
  goreleaser:
    # We don't want ubuntu-24-4 yet, because it is missing some packages
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Get the latest version
        id: latest
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: latest

      - name: Add env vars
        run: |
          echo GORELEASER_CURRENT_TAG=${{ steps.latest.outputs.output }}>> $GITHUB_ENV
          echo RELEASE_NOTES_PATH=.changes/${{ steps.latest.outputs.output }}.md >> $GITHUB_ENV

      - name: Create release
        uses: goreleaser/goreleaser-action@v6
        with:
          args: --clean --release-notes=${{ env.RELEASE_NOTES_PATH }} --skip=validate
        env:
          GORELEASER_CURRENT_TAG: ${{ env.GORELEASER_CURRENT_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: ${{ env.GOPATH }}

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
